<!-- <script>
    const numerator=100;
    denominator=0;
    try{
document.write(numerator/denominator);
document.write("<br>"+a)
    }
    catch(error){
        document.write("An error caught<br>");
        document.write("Error meassge:"+error)
    }
</script> -->

<!-- <script>
    try{
        var a=2;
        if(a==2){
            throw new Error("change value")
        }
        document.write("Ok")
    }
    catch(Error){
        document.write("Error found" + Error.message)
    }
    finally{
        document.write("<br> value of a is 2")
    }
</script> -->


<script>
    try{
        var a=2;
        if(a==10){
            throw new Error("change value")
        }
        document.write("Ok")
    }
    catch(Error){
        document.write("Error found" + Error.message)
    }
    finally{
        document.write("<br> value of a is 2")
    }
</script



